# Generated by Django 5.2.6 on 2025-10-06 13:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='add_datetime_to_instructions',
            new_name='add_datetime_to_context',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='num_history_responses',
            new_name='num_history_runs',
        ),
        migrations.CreateModel(
            name='VaultIngestionTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, help_text='The Celery task ID for the worker processing this task.', max_length=255, null=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique key to prevent duplicate processing on retries.', unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', help_text='The current status of the ingestion task.', max_length=20)),
                ('stage', models.CharField(blank=True, help_text="The current processing stage (e.g., 'downloading', 'parsing', 'embedding').", max_length=50, null=True)),
                ('percent_complete', models.FloatField(default=0.0, help_text='The completion percentage of the task (0.0 to 100.0).')),
                ('attempt_count', models.PositiveIntegerField(default=1, help_text='The number of times this task has been attempted.')),
                ('last_error', models.TextField(blank=True, help_text='The error message from the last failed attempt.', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp when processing started.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when processing completed or terminally failed.', null=True)),
                ('vault_file', models.ForeignKey(help_text='The vault file being ingested.', on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_tasks', to='opie.vaultfile')),
            ],
            options={
                'verbose_name': 'Vault Ingestion Task',
                'verbose_name_plural': 'Vault Ingestion Tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vault_file'], name='opie_vaulti_vault_f_65a0cb_idx'), models.Index(fields=['status', 'stage'], name='opie_vaulti_status_6a8bce_idx'), models.Index(fields=['celery_task_id'], name='opie_vaulti_celery__9e1dde_idx')],
            },
        ),
    ]
