# Generated by Django 5.2.6 on 2025-10-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opie', '0002_vaultingestiontask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='add_datetime_to_instructions',
            new_name='add_datetime_to_context',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='num_history_responses',
            new_name='num_history_runs',
        ),
    ]
