# Generated by Django 5.0.1 on 2024-05-20 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opie", "0002_rename_agent_fields_and_add_vault_ingestion_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChunkingStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "strategy_id",
                    models.CharField(
                        help_text="Machine-readable identifier for the strategy (e.g., 'paper').",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the strategy.", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Explanation of how this strategy works and when to use it.",
                    ),
                ),
                (
                    "strategy_config",
                    models.JSONField(
                        default=dict,
                        help_text='Configuration parameters for the chunking logic. E.g., {"chunk_size": 1000, "chunk_overlap": 200}',
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="chunking_strategy",
            field=models.ForeignKey(
                blank=True,
                help_text="The chunking strategy to use for documents in this knowledge base.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="opie.chunkingstrategy",
            ),
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="chunk_size",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="chunk_overlap",
        ),
    ]