# Generated by Django 5.0.6 on 2025-10-20 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opie', '0005_add_workflow-node-edge_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowedge',
            old_name='workflow_id',
            new_name='workflow',
        ),
        migrations.RenameField(
            model_name='WorkflowNode',
            old_name='workflow_id',
            new_name='workflow',
        ),
    ]
