# Generated by Django 5.2.6 on 2025-10-03 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackOAuthState',
            fields=[
                ('state', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('expire_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'slack_oauth_state',
            },
        ),
        migrations.CreateModel(
            name='SlackWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slack_team_id', models.CharField(max_length=255, unique=True)),
                ('slack_team_name', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('bot_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_enterprise_install', models.BooleanField(default=False)),
                ('bot_id', models.CharField(blank=True, max_length=255, null=True)),
                ('bot_scopes', models.JSONField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_workspaces', to='teams.team')),
            ],
            options={
                'db_table': 'opie_slackworkspace',
            },
        ),
    ]
