# Generated by Django 5.1.5 on 2025-04-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slack_team_id', models.CharField(max_length=255, unique=True)),
                ('slack_team_name', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('bot_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reggie_slackworkspace',
            },
        ),
    ]
