version: '3.8'

services:
  # --- Cloud SQL Auth Proxy ---
  cloudsql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.1
    command: --private-ip --port 5432 --auto-iam-authn bh-opie:australia-southeast1:db0
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/sa-key.json
    volumes:
      - /home/github-actions/.gcp/creds/cloud-run.json:/secrets/sa-key.json:ro
    restart: unless-stopped
    networks:
      - app-network

  # --- PgBouncer Connection Pooler ---
  pgbouncer:
    image: pgbouncer/pgbouncer:latest
    restart: unless-stopped
    environment:
      - DATABASES_HOST=cloudsql-proxy
      - DATABASES_PORT=5432
      - DATABASES_USER=${DB_USER}
      - DATABASES_PASSWORD=${DB_PASS}
      - DATABASES_DBNAME=bh_opie
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=100
      - DEFAULT_POOL_SIZE=20
      - AUTH_TYPE=scram-sha-256
    ports:
      - "6432:6432"
    depends_on:
      - pgbouncer
    networks:
      - app-network

  # --- Redis ---
  redis:
    image: redis:latest
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      retries: 10
    networks:
      - app-network

  # --- Web app ---
  web:
    image: ${ARTIFACT_REGISTRY_URL}/${IMAGE_NAME_WEB}:latest
    container_name: opie-web
    restart: unless-stopped
    volumes:
      - /home/github-actions/.gcp/creds/storage.json:/code/.gcp/creds/storage.json:ro
      # Optional: Uncomment for persistent logs (not recommended for production)
      # - ./logs:/code/logs
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/code/.gcp/creds/storage.json
      - GOOGLE_CLOUD_PROJECT=${PROJECT_ID}
      - FORCE_GCP_DETECTION=${FORCE_GCP_DETECTION}
      - SKIP_COLLECTSTATIC=${SKIP_COLLECTSTATIC}
      - SKIP_DATA_LOADING=${SKIP_DATA_LOADING}
    ports:
      - "8000:8000"
      - "8443:8443"
    dns:
      - 169.254.169.254
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "metadata.google.internal:169.254.169.254"
    depends_on:
      - redis
      - pgbouncer
    networks:
      - app-network

  # --- Celery Worker ---
  celery-worker:
    image: ${ARTIFACT_REGISTRY_URL}/${IMAGE_NAME_WEB}:latest
    container_name: opie-celery-worker
    restart: unless-stopped
    command: celery -A bh_opie worker -l INFO --concurrency=2 --pool=prefork
    volumes:
      - /home/github-actions/.gcp/creds/storage.json:/code/.gcp/creds/storage.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/code/.gcp/creds/storage.json
      - GOOGLE_CLOUD_PROJECT=${PROJECT_ID}
      - FORCE_GCP_DETECTION=${FORCE_GCP_DETECTION}
      - SKIP_COLLECTSTATIC=${SKIP_COLLECTSTATIC}
      - SKIP_DATA_LOADING=${SKIP_DATA_LOADING}
    dns:
      - 169.254.169.254
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "metadata.google.internal:169.254.169.254"
    depends_on:
      - redis
      - pgbouncer
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

  # --- Celery Beat ---
  celery-beat:
    image: ${ARTIFACT_REGISTRY_URL}/${IMAGE_NAME_WEB}:latest
    container_name: opie-celery-beat
    restart: unless-stopped
    command: celery -A bh_opie beat -l INFO
    volumes:
      - /home/github-actions/.gcp/creds/storage.json:/code/.gcp/creds/storage.json:ro
      - celery_beat_data:/code/celerybeat-schedule
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/code/.gcp/creds/storage.json
      - GOOGLE_CLOUD_PROJECT=${PROJECT_ID}
      - FORCE_GCP_DETECTION=${FORCE_GCP_DETECTION}
      - SKIP_COLLECTSTATIC=${SKIP_COLLECTSTATIC}
      - SKIP_DATA_LOADING=${SKIP_DATA_LOADING}
    dns:
      - 169.254.169.254
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "metadata.google.internal:169.254.169.254"
    depends_on:
      - redis
      - pgbouncer
    networks:
      - app-network

  # --- Celery Heavy Worker ---
  celery-worker-heavy:
    image: ${ARTIFACT_REGISTRY_URL}/${IMAGE_NAME_WEB}:latest
    container_name: opie-celery-worker-heavy
    restart: unless-stopped
    command: celery -A bh_opie worker -l INFO --concurrency=1 --pool=prefork --queues=heavy
    volumes:
      - /home/github-actions/.gcp/creds/storage.json:/code/.gcp/creds/storage.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/code/.gcp/creds/storage.json
      - GOOGLE_CLOUD_PROJECT=${PROJECT_ID}
      - FORCE_GCP_DETECTION=${FORCE_GCP_DETECTION}
      - SKIP_COLLECTSTATIC=${SKIP_COLLECTSTATIC}
      - SKIP_DATA_LOADING=${SKIP_DATA_LOADING}
    dns:
      - 169.254.169.254
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "metadata.google.internal:169.254.169.254"
    depends_on:
      - redis
      - pgbouncer
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'

  # --- y-provider ---
  y-provider:
    image: ${ARTIFACT_REGISTRY_URL}/${IMAGE_NAME_Y_PROVIDER}:latest
    container_name: y-provider
    restart: unless-stopped
    env_file:
      - .env.y-provider
    ports:
      - "4444:4444"
    user: "${DOCKER_USER:-1000:1000}"
    depends_on:
      - web
      - redis
    networks:
      - app-network

  # --- Flower (Celery monitoring) ---
  flower:
    image: mher/flower:0.9.7
    container_name: opie-flower
    restart: unless-stopped
    command: flower --broker=redis://redis:6379/0 --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    networks:
      - app-network

# Define network untuk semua services
networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
  celery_beat_data: