version: '3.8'

services:
  # --- Redis ---
  redis:
    image: redis:latest
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      retries: 10
    networks:
      - app-network

  # --- Web app ---
  web:
    image: gcr.io/${PROJECT_ID}/${IMAGE_NAME_WEB}:latest
    container_name: reggie-web
    restart: unless-stopped
    volumes:
      - /home/github-actions/.gcp/creds/storage.json:/code/.gcp/creds/storage.json:ro
      # Optional: Uncomment for persistent logs (not recommended for production)
      # - ./logs:/code/logs
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/code/.gcp/creds/storage.json
    ports:
      - "8000:8000"
      - "8443:8443"
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 169.254.169.254
    depends_on:
      - redis
    networks:
      - app-network

  # --- Celery Worker ---
  celery-worker:
    image: gcr.io/${PROJECT_ID}/${IMAGE_NAME_WEB}:latest
    container_name: reggie-celery-worker
    restart: unless-stopped
    command: celery -A bh_reggie worker -l INFO --concurrency=2 --pool=prefork
    volumes:
      - /home/github-actions/.gcp/creds/storage.json:/code/.gcp/creds/storage.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/code/.gcp/creds/storage.json
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 169.254.169.254
    depends_on:
      - redis
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

  # --- Celery Beat ---
  celery-beat:
    image: gcr.io/${PROJECT_ID}/${IMAGE_NAME_WEB}:latest
    container_name: reggie-celery-beat
    restart: unless-stopped
    command: celery -A bh_reggie beat -l INFO
    volumes:
      - /home/github-actions/.gcp/creds/storage.json:/code/.gcp/creds/storage.json:ro
      - celery_beat_data:/code/celerybeat-schedule
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/code/.gcp/creds/storage.json
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 169.254.169.254
    depends_on:
      - redis
    networks:
      - app-network

  # --- Celery Heavy Worker ---
  celery-worker-heavy:
    image: gcr.io/${PROJECT_ID}/${IMAGE_NAME_WEB}:latest
    container_name: reggie-celery-worker-heavy
    restart: unless-stopped
    command: celery -A bh_reggie worker -l INFO --concurrency=1 --pool=prefork --queues=heavy
    volumes:
      - /home/github-actions/.gcp/creds/storage.json:/code/.gcp/creds/storage.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/code/.gcp/creds/storage.json
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 169.254.169.254
    depends_on:
      - redis
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'

  # --- y-provider ---
  y-provider:
    image: gcr.io/${PROJECT_ID}/${IMAGE_NAME_Y_PROVIDER}:latest
    container_name: y-provider
    restart: unless-stopped
    env_file:
      - .env.y-provider
    ports:
      - "4444:4444"
    user: "${DOCKER_USER:-1000:1000}"
    depends_on:
      - web
      - redis
    networks:
      - app-network

  # --- Flower (Celery monitoring) ---
  flower:
    image: mher/flower:0.9.7
    container_name: reggie-flower
    restart: unless-stopped
    command: flower --broker=redis://redis:6379/0 --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    networks:
      - app-network

# Define network untuk semua services
networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
  celery_beat_data: