# docker-compose.db.yml
# For local/dev use only. Provides stand-alone DB and Redis services for development and testing.

services:
  pgvector:
    image: agnohq/pgvector:16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-bh_reggie}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 2s
      retries: 10

  redis:
    image: redis:latest
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: bash -c 'exec 6<>/dev/tcp/redis/6379'
      interval: 2s
      retries: 10

volumes:
  pgvector_data:
  redis_data: