cli:
  app_directory: apps
  base_model: apps.teams.models.BaseTeamModel
  css_framework: tailwind
  module_path: apps
  template_directory: templates
  use_teams: true
default_context:
  _pegasus_version: 2025.6.2
  author_name: Ben
  bundler: webpack
  ci: github_actions
  css_framework: tailwind
  css_theme: default
  database: postgres
  deploy_platform: none
  description: BH Crypto
  docker_setup: default
  domain_name: localhost:8000
  email: hello@benheath.com.au
  enable_github_login: n
  enable_google_login: y
  enable_twitter_login: n
  front_end_framework: react
  github_username: norfolkpine
  include_static_files: y
  marketing_email_platform: mailchimp
  plugins:
  - group_chat
  post_process: y
  project_name: Ben Heath SaaS
  project_slug: bh_crypto
  python_package_manager: pip-tools
  standalone_front_end: vite
  stripe_payment_mode: checkout
  subscription_billing_model: per_unit
  subscription_pricing_ui: stripe_hosted
  use_2fa: y
  use_admin_docs: y
  use_ai_rules_claude: n
  use_ai_rules_cursor: y
  use_ai_rules_junie: n
  use_api_auth: y
  use_api_keys: y
  use_async: y
  use_celery: y
  use_cloud_media_storage: y
  use_dark_mode: y
  use_debug_toolbar: y
  use_docker: n
  use_ecommerce_example: n
  use_examples: n
  use_flowbite: n
  use_health_checks: y
  use_impersonation: y
  use_sentry: y
  use_shadcn: y
  use_subscriptions: y
  use_teams: y
  use_teams_example: y
  use_translations: y
  use_wagtail: n
