# Generated by Django 5.1.5 on 2025-05-16 05:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_remove_documentaccess_check_document_access_either_user_or_team_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentaccess',
            name='check_document_access_either_user_or_team',
        ),
        migrations.AlterField(
            model_name='documentaccess',
            name='team',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='templateaccess',
            name='team',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='documentaccess',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('team', ''), ('user__isnull', False)), models.Q(('team__gt', ''), ('user__isnull', True)), _connector='OR'), name='check_document_access_either_user_or_team', violation_error_message='Either user or team must be set, not both.'),
        ),
    ]
