# Generated by Django 5.1.5 on 2025-04-08 19:00

import apps.integrations.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('integration_type', models.CharField(choices=[('confluence', 'Confluence'), ('slack', 'Slack'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('gmail', 'Gmail')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('integration_type', 'team'), ('integration_type', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GmailIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('refresh_token', apps.integrations.fields.EncryptedField()),
                ('access_token', apps.integrations.fields.EncryptedField()),
                ('token_expiry', models.DateTimeField()),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='integrations.integration')),
            ],
        ),
        migrations.CreateModel(
            name='ConfluenceIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('username', models.CharField(max_length=255)),
                ('api_key', apps.integrations.fields.EncryptedField()),
                ('space_key', models.CharField(blank=True, max_length=255)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='integrations.integration')),
            ],
        ),
        migrations.CreateModel(
            name='SlackIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.CharField(max_length=255)),
                ('bot_token', apps.integrations.fields.EncryptedField()),
                ('access_token', apps.integrations.fields.EncryptedField()),
                ('channels', models.JSONField(default=list)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='integrations.integration')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', apps.integrations.fields.EncryptedField()),
                ('chat_id', models.CharField(max_length=255)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='integrations.integration')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('api_key', apps.integrations.fields.EncryptedField()),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='integrations.integration')),
            ],
        ),
    ]
