# Generated by Django 5.1.5 on 2025-04-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='integration_type',
            field=models.CharField(choices=[('confluence', 'Confluence'), ('slack', 'Slack'), ('telegram', 'Telegram'), ('gmail', 'Gmail')], max_length=50),
        ),
        migrations.DeleteModel(
            name='WhatsAppIntegration',
        ),
    ]
