version: '3.8'

services:
  y-provider:
    container_name: y-provider
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4444:4444"  # expose the correct port
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    user: "${DOCKER_USER:-1000:1000}"  # safe default if not passed
