#!/bin/bash
# Provision a GCP VM and deploy Django, Redis, and Yjs using Docker Compose
# Usage: bash deploy/provision-vm-and-deploy.sh
set -euo pipefail

# Look for deployment.env in project root (generated by Terraform)
DEPLOY_ENV="$(dirname "$0")/../deployment.env"
if [ -f "$DEPLOY_ENV" ]; then
  echo "Sourcing deployment environment from $DEPLOY_ENV"
  set -a
  source "$DEPLOY_ENV"
  set +a
else
  echo "Warning: deployment.env not found. Run './deploy/generate-deployment-env.sh' first."
  echo "Using default values..."
fi

VM_NAME=${VM_NAME:-opie-stack-vm}
ZONE=${ZONE:-australia-southeast1}
MACHINE_TYPE=${MACHINE_TYPE:-e2-medium}
IMAGE_FAMILY=${IMAGE_FAMILY:-ubuntu-2204-lts}
IMAGE_PROJECT=${IMAGE_PROJECT:-ubuntu-os-cloud}
PROJECT_ID=${PROJECT_ID:-bh-opie}

# 1. VM is now managed by Terraform - verify it exists
if ! gcloud compute instances describe "$VM_NAME" --zone="$ZONE" --project="$PROJECT_ID" >/dev/null 2>&1; then
  echo "ERROR: VM $VM_NAME does not exist!"
  echo "Please run Terraform first to create the infrastructure:"
  echo "  cd infra/envs/prod"
  echo "  terraform init"
  echo "  terraform apply"
  exit 1
else
  echo "VM $VM_NAME exists (managed by Terraform). Proceeding with setup..."
fi

# 2. Docker and Docker Compose are now installed by Terraform startup script
echo "Checking if Docker setup is complete..."
if gcloud compute ssh "ubuntu@$VM_NAME" --zone="$ZONE" --project="$PROJECT_ID" --command="test -f /var/log/docker-setup-complete" 2>/dev/null; then
  echo "Docker and Docker Compose are already installed (via Terraform startup script)."
else
  echo "Docker setup may still be in progress. The startup script runs automatically when the VM is created."
  echo "You can check the status with:"
  echo "  gcloud compute ssh ubuntu@$VM_NAME --zone=$ZONE --project=$PROJECT_ID --command='sudo journalctl -u google-startup-scripts.service -f'"
fi

# 3. Generate SSH key if needed
if [ ! -f "$HOME/.ssh/google_compute_engine" ]; then
  echo "Generating SSH key for gcloud..."
  gcloud compute ssh "$VM_NAME" --zone="$ZONE" --project="$PROJECT_ID" --command="exit"
fi

echo ""
echo "VM is ready for code deployment via GitHub Actions and SSH."
echo "Docker and Docker Compose are installed and ready to use."
