#!/bin/bash
# Deploy bh-opie-llamaindex to Cloud Run from project root
# Usage: ./deploy/deploy-cloudrun-llamaindex.sh
set -euo pipefail

# Look for deployment.env in project root (generated by Terraform)
DEPLOY_ENV="$(dirname "$0")/../deployment.env"
if [ -f "$DEPLOY_ENV" ]; then
  echo "Sourcing deployment environment from $DEPLOY_ENV"
  set -a
  source "$DEPLOY_ENV"
  set +a
else
  echo "Warning: deployment.env not found. Run './deploy/generate-deployment-env.sh' first."
  echo "Using default values..."
fi

# Use variables from deployment.env with fallbacks
PROJECT_ID=${PROJECT_ID:-bh-opie}
REGION=${REGION:-australia-southeast1}
SERVICE_NAME=${SERVICE_NAME:-llamaindex-ingestion}
SERVICE_ACCOUNT=${SERVICE_ACCOUNT:-${CLOUD_RUN_SA}}
IMAGE=${IMAGE:-australia-southeast1-docker.pkg.dev/$PROJECT_ID/containers/$SERVICE_NAME}
SECRET_NAME=${SECRET_NAME:-llamaindex-ingester-env}
SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../cloudrun/bh-opie-llamaindex" && pwd)"

# Verify the secret exists in Secret Manager
echo "[llamaindex] Verifying secret $SECRET_NAME exists in Secret Manager..."
if gcloud secrets describe "$SECRET_NAME" --project="$PROJECT_ID" >/dev/null 2>&1; then
  echo "[llamaindex] Secret $SECRET_NAME exists in Secret Manager"
else
  echo "[llamaindex] ERROR: Secret $SECRET_NAME does not exist in Secret Manager"
  echo "[llamaindex] Please create the secret first with the required environment variables"
  exit 1
fi

# Build Docker image
cd "$SOURCE_DIR"
echo "[llamaindex] Building Docker image..."
docker build -t "$IMAGE" .

# Push image to GCR
echo "[llamaindex] Pushing Docker image to $IMAGE ..."
docker push "$IMAGE"

# Deploy to Cloud Run
echo "[llamaindex] Deploying to Cloud Run..."
gcloud run deploy "$SERVICE_NAME" \
  --image="$IMAGE" \
  --region="$REGION" \
  --platform=managed \
  --service-account="$SERVICE_ACCOUNT" \
  --memory=2Gi \
  --timeout=900 \
  --allow-unauthenticated \
  --set-env-vars=GCP_PROJECT="$PROJECT_ID",DB_CONNECTION_NAME="$DB_CONNECTION_NAME",STATIC_BUCKET="$STATIC_BUCKET",MEDIA_BUCKET="$MEDIA_BUCKET",DOCS_BUCKET="$DOCS_BUCKET" \
  --set-secrets=ENV_VARS="$SECRET_NAME:latest" \
  --project="$PROJECT_ID"

echo "[llamaindex] Deployment complete."
