# Generated by Django 5.1.5 on 2025-05-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_language_default_to_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], default=None, help_text='The language in which the user wants to see the interface.', max_length=10, null=True, verbose_name='language'),
        ),
    ]
