# Generated by Django 5.2.2 on 2025-08-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_language_customuser_timezone_and_more'),
        ('users', '0020_alter_customuser_language'),
    ]

    operations = [
    ]
