# Generated by Django 5.1.5 on 2025-04-06 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reggie', '0002_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentexpectedoutput',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='reggie.agent'),
        ),
        migrations.AddField(
            model_name='agentexpectedoutput',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agent',
            name='expected_output',
            field=models.ForeignKey(blank=True, help_text='The predefined expected output template assigned to this agent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='reggie.agentexpectedoutput'),
        ),
        migrations.AddField(
            model_name='agentinstruction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agent',
            name='instructions',
            field=models.ForeignKey(blank=True, help_text='The predefined instructions assigned to this agent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='reggie.agentinstruction'),
        ),
        migrations.AddField(
            model_name='agentparameter',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='reggie.agent'),
        ),
        migrations.AddField(
            model_name='agentuiproperties',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ui_properties', to='reggie.agent'),
        ),
        migrations.AddField(
            model_name='agent',
            name='capabilities',
            field=models.ManyToManyField(blank=True, related_name='agents', to='reggie.capability'),
        ),
        migrations.AddField(
            model_name='agent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='reggie.category'),
        ),
        migrations.AddField(
            model_name='document',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='teams.team'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='reggie.documenttag'),
        ),
        migrations.AddField(
            model_name='agent',
            name='knowledge_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reggie.knowledgebase'),
        ),
        migrations.AddField(
            model_name='agent',
            name='model',
            field=models.ForeignKey(blank=True, help_text='AI model used by the agent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='reggie.modelprovider'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team this project belongs to (optional if personal).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='teams.team'),
        ),
        migrations.AddField(
            model_name='slackworkspace',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_workspaces', to='teams.team'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='reggie.tag'),
        ),
        migrations.AddField(
            model_name='teamproject',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_team_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamproject',
            name='tags',
            field=models.ManyToManyField(blank=True, to='reggie.tag'),
        ),
        migrations.AddField(
            model_name='teamproject',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='teamtoolcredential',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_tool_credentials', to='reggie.agent'),
        ),
        migrations.AddField(
            model_name='teamtoolcredential',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_credentials', to='teams.team'),
        ),
        migrations.AddField(
            model_name='teamtoolcredential',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_credentials', to='reggie.tool'),
        ),
        migrations.AddField(
            model_name='usertoolcredential',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tool_credentials', to='reggie.agent'),
        ),
        migrations.AddField(
            model_name='usertoolcredential',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credentials', to='reggie.tool'),
        ),
        migrations.AddField(
            model_name='usertoolcredential',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='website',
            name='owner',
            field=models.ForeignKey(help_text='User who added this website.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_websites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='website',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Optional tags for organizing websites.', to='reggie.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='agentparameter',
            unique_together={('agent', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='teamtoolcredential',
            unique_together={('team', 'tool', 'agent')},
        ),
        migrations.AlterUniqueTogether(
            name='usertoolcredential',
            unique_together={('user', 'tool', 'agent')},
        ),
    ]
