# Generated by Django 5.1.5 on 2025-03-18 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0002_teamproject_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('google', 'Google'), ('anthropic', 'Anthropic'), ('groq', 'Groq')], help_text='LLM provider (e.g., OpenAI, Google, Anthropic, Groq).', max_length=20)),
                ('model_name', models.CharField(help_text='Model identifier (e.g., gpt-4o, gemini-pro, claude-3).', max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this model is available for use.')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='debug_mode',
            field=models.BooleanField(default=False, help_text='Enable debug mode for logging.'),
        ),
        migrations.AddField(
            model_name='agent',
            name='num_history_responses',
            field=models.IntegerField(default=3, help_text='Number of past responses to keep in chat memory.'),
        ),
        migrations.AddField(
            model_name='agent',
            name='session_table',
            field=models.CharField(default='agent_session_939c19a99deb', editable=False, help_text='Table name for session persistence.', max_length=255),
        ),
        migrations.AddField(
            model_name='agent',
            name='unique_code',
            field=models.CharField(default='26300891b999', help_text='Unique identifier for the agent, used for session storage.', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='model',
            field=models.ForeignKey(blank=True, help_text='AI model used by the agent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='reggie.modelprovider'),
        ),
    ]
