# Generated by Django 5.1.5 on 2025-05-21 04:55

import apps.reggie.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0003_initial'),
        ('teams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_vault',
            field=models.BooleanField(default=False, help_text='Is this file a vault file?'),
        ),
        migrations.AddField(
            model_name='file',
            name='vault_project',
            field=models.ForeignKey(blank=True, help_text='Vault project for this file (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_vault_files', to='reggie.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Direct users with access to this project.', related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='shared_with_teams',
            field=models.ManyToManyField(blank=True, help_text='Teams with access to this project.', related_name='shared_projects', to='teams.team'),
        ),
        migrations.AddField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text="Upload a file to the user's file library or vault. Supported types: pdf, docx, txt, csv, json", max_length=1024, upload_to=apps.reggie.models.choose_upload_path),
        ),
        migrations.CreateModel(
            name='VaultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1024, upload_to=apps.reggie.models.vault_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_files', to='reggie.project')),
                ('shared_with_teams', models.ManyToManyField(blank=True, related_name='shared_team_vault_files', to='teams.team')),
                ('shared_with_users', models.ManyToManyField(blank=True, related_name='shared_vault_files', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_files', to='teams.team')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vault File',
                'verbose_name_plural': 'Vault Files',
                'ordering': ['-created_at'],
            },
        ),
    ]
