# Generated by Django 5.2.2 on 2025-08-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reggie", "0003_add_hierarchical_collections"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={
                "ordering": ["collection", "collection_order", "volume_number", "part_number", "title"],
                "permissions": [
                    ("can_ingest_files", "Can ingest files into knowledge base"),
                    ("can_manage_global_files", "Can manage global files"),
                ],
            },
        ),
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="file",
            name="part_number",
            field=models.CharField(
                blank=True, help_text="Part or section number (e.g., 'Part A', 'Section 1')", max_length=20, null=True
            ),
        ),
    ]
