# Generated by Django 5.1.5 on 2025-04-12 10:13

import apps.reggie.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='knowledge_table',
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_knowledge_id',
            field=models.CharField(blank=True, editable=False, help_text='Table name for knowledge base persistence, derived from unique_code.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='knowledgebase_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique slugified identifier used for referencing and table naming.', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='model_provider',
            field=models.ForeignKey(blank=True, help_text='LLM provider to use for embeddings in this knowledge base.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reggie.modelprovider'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='unique_code',
            field=models.UUIDField(default=apps.reggie.models.generate_full_uuid, editable=False, help_text='Globally unique identifier for the knowledge base.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='vector_table_name',
            field=models.CharField(blank=True, editable=False, help_text='Postgres vector table name used for embeddings.', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='KnowledgeBasePdfURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('is_enabled', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('kb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_urls', to='reggie.knowledgebase')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('kb', 'url')},
            },
        ),
    ]
