# Generated by Django 5.1.5 on 2025-03-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0003_modelprovider_agent_debug_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='session_table',
            field=models.CharField(default='agent_session_c4f58f2f077d', editable=False, help_text='Table name for session persistence.', max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='unique_code',
            field=models.CharField(default='ccada4dcd1ef', editable=False, help_text='Unique identifier for the agent, used for session storage.', max_length=20, unique=True),
        ),
    ]
