# Generated by Django 5.1.5 on 2025-03-24 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0004_alter_agent_session_table_alter_agent_unique_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='session_table',
            field=models.CharField(default='agent_session_e40c66223758', editable=False, help_text='Table name for session persistence.', max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='unique_code',
            field=models.CharField(default='750362f23414', editable=False, help_text='Unique identifier for the agent, used for session storage.', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='AgentExpectedOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_output', models.TextField()),
                ('category', models.CharField(choices=[('Scope & Knowledge Boundaries', 'Scope & Knowledge Boundaries'), ('Information Retrieval & Accuracy', 'Information Retrieval & Accuracy'), ('Response Handling & Formatting', 'Response Handling & Formatting'), ('Compliance-Specific Instructions', 'Compliance-Specific Instructions'), ('Personality', 'Personality'), ('Process', 'Process'), ('Improvement', 'Improvement')], default='Response Handling & Formatting', max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_global', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='reggie.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
