# Generated by Django 5.1.5 on 2025-03-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0004_alter_agent_session_table_alter_agent_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT'), ('csv', 'CSV'), ('json', 'JSON'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='agent',
            name='session_table',
            field=models.CharField(default='agent_session_82b7cc4bb483', editable=False, help_text='Table name for session persistence.', max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='unique_code',
            field=models.CharField(default='193df4b32f6f', editable=False, help_text='Unique identifier for the agent, used for session storage.', max_length=20, unique=True),
        ),
    ]
