# Generated by Django 5.1.5 on 2025-04-12 10:36

import apps.reggie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0004_remove_agent_knowledge_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='unique_code',
            field=models.UUIDField(default=apps.reggie.models.generate_full_uuid, editable=False, help_text='Globally unique identifier for the knowledge base.', unique=True),
        ),
    ]
