# Generated by Django 5.1.5 on 2025-04-12 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0005_alter_knowledgebase_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='model_provider',
            field=models.ForeignKey(help_text='LLM provider to use for embeddings in this knowledge base.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reggie.modelprovider'),
        ),
    ]
