# Generated by Django 5.2.2 on 2025-09-11 23:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0005_collection_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultfile',
            name='is_folder',
            field=models.BooleanField(default=False, help_text='Whether this entry represents a folder'),
        ),
        migrations.CreateModel(
            name='VaultChatSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Vault Chat', help_text='Title of the vault chat session', max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_chat_sessions', to='reggie.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VaultChatMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('sources', models.JSONField(blank=True, help_text='Source documents and metadata for assistant responses', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='reggie.vaultchatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vaultchatsession',
            index=models.Index(fields=['-updated_at'], name='reggie_vaul_updated_06065f_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultchatsession',
            index=models.Index(fields=['project', 'user'], name='reggie_vaul_project_39576c_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultchatmessage',
            index=models.Index(fields=['session', 'created_at'], name='reggie_vaul_session_6a5076_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultchatmessage',
            index=models.Index(fields=['role'], name='reggie_vaul_role_1434fa_idx'),
        ),
    ]
