# Generated by Django 5.1.5 on 2025-03-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0005_document_file_type_alter_agent_session_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='session_table',
            field=models.CharField(default='agent_session_6dffa8c33017', editable=False, help_text='Table name for session persistence.', max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='unique_code',
            field=models.CharField(default='9198b45ecca5', editable=False, help_text='Unique identifier for the agent, used for session storage.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT'), ('csv', 'CSV'), ('json', 'JSON'), ('other', 'Other')], default='pdf', help_text='Type of the file. Supported types: pdf, docx, txt, csv, json', max_length=10),
        ),
    ]
