# Generated by Django 5.1.5 on 2025-06-06 02:59

from django.db import migrations, models

import apps.reggie.models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0005_alter_vaultfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultfile',
            name='size',
            field=models.BigIntegerField(blank=True, help_text='Size of file in bytes', null=True),
        ),
        migrations.AddField(
            model_name='vaultfile',
            name='type',
            field=models.CharField(blank=True, help_text='File MIME type or extension', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vaultfile',
            name='file',
            field=models.FileField(max_length=1024, upload_to=apps.reggie.models.vault_file_path),
        ),
    ]
