# Generated by Django 5.2.2 on 2025-09-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0005_collection_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultfile',
            name='is_folder',
            field=models.IntegerField(default=0, help_text="1 if this is a folder, 0 if it's a file"),
        ),
        migrations.AddField(
            model_name='vaultfile',
            name='parent_id',
            field=models.BigIntegerField(default=0, help_text='ID of parent folder, 0 if root level'),
        ),
    ]
