# Generated by Django 5.1.5 on 2025-03-24 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0005_alter_agent_session_table_alter_agent_unique_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='expected_output',
            field=models.ForeignKey(blank=True, help_text='The predefined expected output template assigned to this agent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='reggie.agentexpectedoutput'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='session_table',
            field=models.CharField(default='agent_session_c0744c0a8275', editable=False, help_text='Table name for session persistence.', max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='unique_code',
            field=models.CharField(default='6c02be5e4f66', editable=False, help_text='Unique identifier for the agent, used for session storage.', max_length=20, unique=True),
        ),
    ]
