# Generated by Django 5.2.2 on 2025-09-11 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0006_add_is_folder_to_vaultfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultfile',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent folder for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='reggie.vaultfile'),
        ),
    ]
