# Generated by Django 5.1.5 on 2025-03-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0006_agent_expected_output_alter_agent_session_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='session_table',
            field=models.CharField(default='agent_session_44b0d394aec1', editable=False, help_text='Table name for session persistence.', max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='unique_code',
            field=models.CharField(default='d4b36456c5ac', editable=False, help_text='Unique identifier for the agent, used for session storage.', max_length=20, unique=True),
        ),
    ]
