# Generated by Django 5.1.5 on 2025-06-06 04:41

import apps.reggie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0006_vaultfile_size_vaultfile_type_alter_vaultfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultfile',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename as uploaded by user', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='vaultfile',
            name='file',
            field=models.FileField(max_length=1024, upload_to=apps.reggie.models.vault_file_path),
        ),
    ]
