# Generated by Django 5.2.2 on 2025-09-07 18:07

import apps.reggie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0006_add_folder_fields_to_vaultfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultfile',
            name='file',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=apps.reggie.models.vault_file_path),
        ),
    ]
