# Generated by Django 5.1.5 on 2025-04-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0006_alter_knowledgebase_model_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='add_history_to_messages',
            field=models.BooleanField(default=True),
        ),
    ]
