# Generated by Django 5.1.5 on 2025-06-11 06:14

import apps.reggie.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0007_vaultfile_original_filename_alter_vaultfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='filesize',
            field=models.BigIntegerField(default=0, help_text='Size of the file in bytes (mirrors file_size, for API compatibility)'),
        ),
        migrations.AlterField(
            model_name='vaultfile',
            name='file',
            field=models.FileField(max_length=1024, upload_to=apps.reggie.models.vault_file_path),
        ),
        migrations.AddField(
            model_name='file',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Collection this file belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='reggie.collection'),
        ),
    ]
