# Generated by Django 5.1.5 on 2025-03-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0007_alter_agent_session_table_alter_agent_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='cite_knowledge',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentinstruction',
            name='is_template',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='session_table',
            field=models.CharField(default='agent_session_58d6d5515e14', editable=False, help_text='Table name for session persistence.', max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='unique_code',
            field=models.CharField(default='011074f86890', editable=False, help_text='Unique identifier for the agent, used for session storage.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='agentexpectedoutput',
            name='category',
            field=models.CharField(choices=[('Scope & Knowledge Boundaries', 'Scope & Knowledge Boundaries'), ('Information Retrieval & Accuracy', 'Information Retrieval & Accuracy'), ('Response Handling & Formatting', 'Response Handling & Formatting'), ('Compliance-Specific Instructions', 'Compliance-Specific Instructions'), ('Personality', 'Personality'), ('Process', 'Process'), ('Improvement', 'Improvement'), ('Template', 'Template')], default='Response Handling & Formatting', max_length=50),
        ),
        migrations.AlterField(
            model_name='agentinstruction',
            name='category',
            field=models.CharField(choices=[('Scope & Knowledge Boundaries', 'Scope & Knowledge Boundaries'), ('Information Retrieval & Accuracy', 'Information Retrieval & Accuracy'), ('Response Handling & Formatting', 'Response Handling & Formatting'), ('Compliance-Specific Instructions', 'Compliance-Specific Instructions'), ('Personality', 'Personality'), ('Process', 'Process'), ('Improvement', 'Improvement'), ('Template', 'Template')], default='Process', max_length=50),
        ),
    ]
