# Generated by Django 5.1.5 on 2025-06-13 05:39

import apps.reggie.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0008_collection_file_filesize_alter_vaultfile_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultfile',
            name='file',
            field=models.FileField(max_length=1024, upload_to=apps.reggie.models.vault_file_path),
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.CharField(help_text='ID of the chat message or response being reviewed.', max_length=128)),
                ('feedback_type', models.CharField(choices=[('up', 'Thumbs Up'), ('down', 'Thumbs Down')], max_length=8)),
                ('feedback_text', models.TextField(blank=True, help_text='Optional user feedback.', null=True)),
                ('session', models.ForeignKey(help_text='Related chat session.', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='reggie.chatsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
