# Generated by Django 5.2.2 on 2025-09-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0008_aiconversation_aiprocessingqueue_vaultfileinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vault_vector_table',
            field=models.CharField(blank=True, help_text='Vector table name for Vault file embeddings', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vaultfile',
            name='embedded_at',
            field=models.DateTimeField(blank=True, help_text='When the file was embedded', null=True),
        ),
        migrations.AddField(
            model_name='vaultfile',
            name='embedding_error',
            field=models.TextField(blank=True, help_text='Error message if embedding failed', null=True),
        ),
        migrations.AddField(
            model_name='vaultfile',
            name='embedding_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', help_text='Current embedding status', max_length=20),
        ),
        migrations.AddField(
            model_name='vaultfile',
            name='is_embedded',
            field=models.BooleanField(default=False, help_text='Whether file content has been embedded'),
        ),
    ]
