# Generated by Django 5.1.5 on 2025-04-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0008_alter_knowledgebase_knowledge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='knowledge_type',
            field=models.CharField(choices=[('agno_pgvector', 'Agno PGVector (default)'), ('llamaindex', 'LlamaIndex VectorStore'), ('arxiv', 'ArXiv Papers'), ('combined', 'Combined Knowledge Base'), ('csv', 'CSV Files'), ('document', 'Document Files (DOCX)'), ('json', 'JSON Files'), ('langchain', 'LangChain Retriever'), ('pdf', 'Local PDF Files'), ('pdf_url', 'PDF Files from URLs'), ('s3_pdf', 'PDF Files from S3'), ('s3_text', 'Text Files from S3'), ('text', 'Local Text Files'), ('website', 'Website Data'), ('wikipedia', 'Wikipedia Articles'), ('other', 'Other Knowledge Type')], default='llamaindex', help_text='Defines how this knowledge base is structured (e.g., PDFs, SQL, API, etc.).', max_length=20),
        ),
    ]
