# Generated by Django 5.1.5 on 2025-03-28 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0006_alter_agent_session_table_alter_agent_unique_code_and_more'),
        ('reggie', '0009_alter_agent_session_table_alter_agent_unique_code_and_more'),
    ]

    operations = [
    ]
