# Generated by Django 5.2.2 on 2025-09-16 21:20

import apps.reggie.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0010_projectinstruction_project_instruction'),
        ('teams', '0002_add_djstripe_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(blank=True, help_text='Session ID for grouping related requests', max_length=255, null=True)),
                ('conversation_id', models.CharField(blank=True, help_text='Conversation ID if applicable', max_length=255, null=True)),
                ('agent_id', models.IntegerField(blank=True, help_text='Agent ID if applicable', null=True)),
                ('provider', models.CharField(blank=True, help_text='LLM provider (e.g., openai, anthropic)', max_length=100, null=True)),
                ('model', models.CharField(blank=True, help_text='Model name (e.g., gpt-4, claude-3)', max_length=100, null=True)),
                ('operation_type', models.CharField(choices=[('chat', 'Chat'), ('embedding', 'Embedding'), ('rerank', 'Rerank'), ('tool', 'Tool'), ('insights', 'Insights')], default='chat', help_text='Type of operation that used tokens', max_length=20)),
                ('prompt_tokens', models.IntegerField(default=0, help_text='Number of prompt/input tokens')),
                ('completion_tokens', models.IntegerField(default=0, help_text='Number of completion/output tokens')),
                ('total_tokens', models.IntegerField(default=0, help_text='Total tokens used')),
                ('request_id', models.CharField(blank=True, help_text='Unique request ID for idempotency', max_length=255, null=True)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0.0, help_text='Estimated cost in USD', max_digits=10)),
            ],
            options={
                'verbose_name': 'Token Usage',
                'verbose_name_plural': 'Token Usage Records',
                'db_table': 'reggie_token_usage',
            },
        ),
        migrations.RenameIndex(
            model_name='projectinstruction',
            new_name='reggie_proj_instruc_3e7a18_idx',
            old_name='reggie_proj_instruc_9f8d2a_idx',
        ),
        migrations.RenameIndex(
            model_name='projectinstruction',
            new_name='reggie_proj_created_52ca01_idx',
            old_name='reggie_proj_created_2b4e1c_idx',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text="Upload a file to the user's file library or vault. Supported types: pdf, docx, xlsx, txt, csv, json, md, jpeg, jpg, png, gif", max_length=1024, upload_to=apps.reggie.models.choose_upload_path),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('xlsx', 'XLSX'), ('txt', 'TXT'), ('csv', 'CSV'), ('json', 'JSON'), ('md', 'Markdown'), ('jpeg', 'JPEG'), ('jpg', 'JPG'), ('png', 'PNG'), ('gif', 'GIF'), ('other', 'Other')], default='pdf', help_text='Detected type of the uploaded file.', max_length=10),
        ),
        migrations.AddField(
            model_name='tokenusage',
            name='team',
            field=models.ForeignKey(help_text='Team that owns this usage', on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='teams.team'),
        ),
        migrations.AddField(
            model_name='tokenusage',
            name='user',
            field=models.ForeignKey(help_text='User who generated the tokens', on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tokenusage',
            index=models.Index(fields=['user', 'created_at'], name='reggie_toke_user_id_29dc31_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusage',
            index=models.Index(fields=['team', 'created_at'], name='reggie_toke_team_id_ddc775_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusage',
            index=models.Index(fields=['operation_type', 'created_at'], name='reggie_toke_operati_3e2d70_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusage',
            index=models.Index(fields=['provider', 'model'], name='reggie_toke_provide_76017d_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusage',
            index=models.Index(fields=['request_id'], name='reggie_toke_request_69d9d2_idx'),
        ),
    ]
