# Generated by Django 5.1.5 on 2025-04-29 14:41

import apps.reggie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0010_rename_documenttag_filetag_file_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text="Upload a file to the user's file library. Supported types: pdf, docx, txt, csv, json", upload_to=apps.reggie.models.user_file_path),
        ),
    ]
