# Generated by Django 5.1.5 on 2025-03-29 08:16

import apps.reggie.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0010_merge_20250328_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='agent',
            name='session_table',
            field=models.CharField(default='agent_session_1f0964d29736', editable=False, help_text='Table name for session persistence.', max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='unique_code',
            field=models.CharField(default='5a3e45b793b6', editable=False, help_text='Unique identifier for the agent, used for session storage.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text="Upload a file to the user's document library. Supported types: pdf, docx, txt, csv, json", upload_to=apps.reggie.models.user_document_path),
        ),
        migrations.CreateModel(
            name='AgentUIProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('text_color', models.CharField(blank=True, max_length=255, null=True)),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ui_properties', to='reggie.agent')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='capabilities',
            field=models.ManyToManyField(related_name='agents', to='reggie.capability'),
        ),
        migrations.AddField(
            model_name='agent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='reggie.category'),
        ),
    ]
