# Generated by Django 5.2.2 on 2025-09-19 20:32

from django.db import migrations, models


def convert_to_boolean(apps, schema_editor):
    """Convert integer values (0, 1) to boolean (False, True)"""
    VaultFile = apps.get_model('reggie', 'VaultFile')
    db_alias = schema_editor.connection.alias

    # Convert all is_folder values
    # 0 -> False, 1 -> True
    VaultFile.objects.using(db_alias).all().update(
        is_folder_temp=models.Case(
            models.When(is_folder=1, then=True),
            models.When(is_folder=0, then=False),
            default=False
        )
    )


def convert_to_integer(apps, schema_editor):
    """Reverse operation: convert boolean back to integer"""
    VaultFile = apps.get_model('reggie', 'VaultFile')
    db_alias = schema_editor.connection.alias

    # Convert all is_folder values
    # False -> 0, True -> 1
    VaultFile.objects.using(db_alias).all().update(
        is_folder_temp=models.Case(
            models.When(is_folder=True, then=1),
            models.When(is_folder=False, then=0),
            default=0
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0010_projectinstruction_project_instruction'),
    ]

    operations = [
        # Step 1: Add a temporary boolean field
        migrations.AddField(
            model_name='vaultfile',
            name='is_folder_temp',
            field=models.BooleanField(default=False),
        ),

        # Step 2: Copy data from integer field to boolean field
        migrations.RunPython(
            code=convert_to_boolean,
            reverse_code=convert_to_integer,
        ),

        # Step 3: Remove the old integer field
        migrations.RemoveField(
            model_name='vaultfile',
            name='is_folder',
        ),

        # Step 4: Rename the temporary field to the original name
        migrations.RenameField(
            model_name='vaultfile',
            old_name='is_folder_temp',
            new_name='is_folder',
        ),

        # Step 5: Alter the field to have the correct definition
        migrations.AlterField(
            model_name='vaultfile',
            name='is_folder',
            field=models.BooleanField(default=False, help_text="True if this is a folder, False if it's a file"),
        ),
    ]
