# Generated by Django 5.1.5 on 2025-03-30 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0011_capability_category_alter_agent_session_table_and_more'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capability',
            options={'verbose_name_plural': 'Capabilities'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='session_table',
            field=models.CharField(default='agent_session_cbbc64ead3d2', editable=False, help_text='Table name for session persistence.', max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='unique_code',
            field=models.CharField(default='a4a591a39d61', editable=False, help_text='Unique identifier for the agent, used for session storage.', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='SlackWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_team_id', models.CharField(max_length=255, unique=True)),
                ('slack_team_name', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('bot_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_workspaces', to='teams.team')),
            ],
        ),
    ]
