# Generated by Django 5.2.2 on 2025-09-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0011_tokenusage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenusage',
            name='agent_id',
            field=models.CharField(blank=True, help_text='Agent ID if applicable', max_length=255, null=True),
        ),
    ]
