# Generated by Django 5.1.5 on 2025-06-18 13:21

import apps.reggie.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0011_collection_updated_at_alter_vaultfile_file'),
        ('teams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who created this knowledge base.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vaultfile',
            name='file',
            field=models.FileField(max_length=1024, upload_to=apps.reggie.models.vault_file_path),
        ),
        migrations.CreateModel(
            name='KnowledgeBasePermission',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('owner', 'Owner')], default='viewer', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kb_team_links', to=settings.AUTH_USER_MODEL)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_links', to='reggie.knowledgebase')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledgebase_permission_links', to='teams.team')),
            ],
            options={
                'verbose_name': 'Knowledge Base Permission',
                'verbose_name_plural': 'Knowledge Base Permissions',
                'unique_together': {('knowledge_base', 'team')},
            },
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Teams with access to this knowledge base via permissions.', related_name='knowledge_bases', through='reggie.KnowledgeBasePermission', to='teams.team'),
        ),
    ]
