# Generated by Django 5.1.5 on 2025-04-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0011_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='gcs_path',
            field=models.CharField(blank=True, help_text='GCS path where the file is stored.', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='is_ingested',
            field=models.BooleanField(default=False, help_text='Whether the file has been successfully ingested into the vector database.'),
        ),
    ]
