# Generated by Django 5.1.5 on 2025-03-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0012_alter_capability_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='session_table',
            field=models.CharField(default='agent_session_5f296c3874d0', editable=False, help_text='Table name for session persistence.', max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='unique_code',
            field=models.CharField(default='c9a6c9c27e3b', editable=False, help_text='Unique identifier for the agent, used for session storage.', max_length=20, unique=True),
        ),
    ]
