# Generated by Django 5.1.5 on 2025-06-24 03:14

import apps.reggie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0012_knowledgebase_uploaded_by_alter_vaultfile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='vector_table_name',
            field=models.CharField(blank=True, editable=False, help_text='Postgres vector table name used for embeddings.', max_length=255),
        ),
        migrations.AlterField(
            model_name='vaultfile',
            name='file',
            field=models.FileField(max_length=1024, upload_to=apps.reggie.models.vault_file_path),
        ),
    ]
