# Generated by Django 5.1.5 on 2025-04-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0012_file_gcs_path_file_is_ingested'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text="Upload a file to the user's file library. Supported types: pdf, docx, txt, csv, json", upload_to='user_files/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT'), ('csv', 'CSV'), ('json', 'JSON'), ('other', 'Other')], default='pdf', help_text='Detected type of the uploaded file.', max_length=10),
        ),
        migrations.AlterField(
            model_name='file',
            name='gcs_path',
            field=models.CharField(blank=True, help_text='Full GCS path of the uploaded file.', max_length=1024, null=True),
        ),
    ]
