# Generated by Django 5.1.5 on 2025-07-06 02:45

from django.db import migrations

def delete_all_vaultfiles(apps, schema_editor):
    apps.get_model('reggie', 'VaultFile').objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0013_alter_knowledgebase_vector_table_name_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_all_vaultfiles, reverse_code=migrations.RunPython.noop),
    ]
