# Generated by Django 5.1.5 on 2025-07-03 12:38

from django.db import migrations, models

import apps.reggie.models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0013_alter_knowledgebase_vector_table_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='default_reasoning',
            field=models.BooleanField(default=False, help_text='Enable chain-of-thought reasoning by default for this agent.'),
        ),
        migrations.AlterField(
            model_name='vaultfile',
            name='file',
            field=models.FileField(max_length=1024, upload_to=apps.reggie.models.vault_file_path),
        ),
    ]
