# Generated by Django 5.1.5 on 2025-03-30 02:38

import apps.reggie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0013_alter_agent_session_table_alter_agent_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='session_table',
            field=models.CharField(default=apps.reggie.models.generate_session_table, editable=False, help_text='Table name for session persistence.', max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='unique_code',
            field=models.CharField(default=apps.reggie.models.generate_unique_code, editable=False, help_text='Unique identifier for the agent, used for session storage.', max_length=20, unique=True),
        ),
    ]
