# Generated by Django 5.1.5 on 2025-04-29 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0013_alter_file_options_alter_file_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='knowledge_base',
            field=models.ForeignKey(blank=True, help_text='Knowledge base this file is attached to (if used for ingestion).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='reggie.knowledgebase'),
        ),
    ]
