# Generated by Django 5.1.5 on 2025-05-05 10:33

import apps.reggie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0014_file_knowledge_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='auto_ingest',
            field=models.BooleanField(default=False, help_text='Whether to automatically ingest this file after upload.'),
        ),
        migrations.AddField(
            model_name='file',
            name='ingestion_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the ingestion process completed.', null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='ingestion_error',
            field=models.TextField(blank=True, help_text='Error message if ingestion failed.', null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='ingestion_progress',
            field=models.FloatField(default=0.0, help_text='Current progress of ingestion (0-100)'),
        ),
        migrations.AddField(
            model_name='file',
            name='ingestion_started_at',
            field=models.DateTimeField(blank=True, help_text='When the ingestion process started.', null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='ingestion_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the ingestion process.', max_length=20),
        ),
        migrations.AddField(
            model_name='file',
            name='processed_docs',
            field=models.IntegerField(default=0, help_text='Number of documents processed'),
        ),
        migrations.AddField(
            model_name='file',
            name='total_docs',
            field=models.IntegerField(default=0, help_text='Total number of documents to process'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text="Upload a file to the user's file library. Supported types: pdf, docx, txt, csv, json", upload_to=apps.reggie.models.user_file_path),
        ),
    ]
