# Generated by Django 5.1.5 on 2025-07-06 15:25

import apps.reggie.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0014_agent_default_enable_reasoning_alter_vaultfile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultfile',
            name='file',
            field=models.FileField(max_length=1024, upload_to=apps.reggie.models.vault_file_path),
        ),
        migrations.CreateModel(
            name='EphemeralFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to=apps.reggie.models.chat_file_path)),
                ('name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ephemeral_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='reggie_ephe_session_4d02c4_idx')],
            },
        ),
    ]
