# Generated by Django 5.1.5 on 2025-03-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0014_alter_agent_session_table_alter_agent_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentexpectedoutput',
            name='category',
            field=models.CharField(choices=[('Scope & Knowledge Boundaries', 'Scope & Knowledge Boundaries'), ('Information Retrieval & Accuracy', 'Information Retrieval & Accuracy'), ('Response Handling & Formatting', 'Response Handling & Formatting'), ('Compliance-Specific Instructions', 'Compliance-Specific Instructions'), ('Personality', 'Personality'), ('Process', 'Process'), ('Improvement', 'Improvement'), ('Template', 'Template'), ('User Instructions', 'User Instructions')], default='Response Handling & Formatting', max_length=50),
        ),
        migrations.AlterField(
            model_name='agentinstruction',
            name='category',
            field=models.CharField(choices=[('Scope & Knowledge Boundaries', 'Scope & Knowledge Boundaries'), ('Information Retrieval & Accuracy', 'Information Retrieval & Accuracy'), ('Response Handling & Formatting', 'Response Handling & Formatting'), ('Compliance-Specific Instructions', 'Compliance-Specific Instructions'), ('Personality', 'Personality'), ('Process', 'Process'), ('Improvement', 'Improvement'), ('Template', 'Template'), ('User Instructions', 'User Instructions')], default='Template', max_length=50),
        ),
    ]
