# Generated by Django 5.1.5 on 2025-07-06 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0014_delete_all_vaultfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultfile',
            name='original_filename',
        ),
        migrations.RemoveField(
            model_name='vaultfile',
            name='size',
        ),
        migrations.RemoveField(
            model_name='vaultfile',
            name='type',
        ),
        migrations.AlterField(
            model_name='vaultfile',
            name='file',
            field=models.OneToOneField(blank=True, help_text='Reference to the main File object for this vault file.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_file', to='reggie.file'),
        ),
    ]
