# Generated by Django 5.1.5 on 2025-03-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0015_alter_agentexpectedoutput_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinstruction',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Flag for platform/system-level instructions.'),
        ),
        migrations.AlterField(
            model_name='agentexpectedoutput',
            name='category',
            field=models.CharField(choices=[('Scope & Knowledge Boundaries', 'Scope & Knowledge Boundaries'), ('Information Retrieval & Accuracy', 'Information Retrieval & Accuracy'), ('Response Handling & Formatting', 'Response Handling & Formatting'), ('Compliance-Specific Instructions', 'Compliance-Specific Instructions'), ('Personality', 'Personality'), ('Process', 'Process'), ('Improvement', 'Improvement'), ('Template', 'Template'), ('User', 'User-Defined Primary Instruction')], default='Response Handling & Formatting', max_length=50),
        ),
        migrations.AlterField(
            model_name='agentinstruction',
            name='category',
            field=models.CharField(choices=[('Scope & Knowledge Boundaries', 'Scope & Knowledge Boundaries'), ('Information Retrieval & Accuracy', 'Information Retrieval & Accuracy'), ('Response Handling & Formatting', 'Response Handling & Formatting'), ('Compliance-Specific Instructions', 'Compliance-Specific Instructions'), ('Personality', 'Personality'), ('Process', 'Process'), ('Improvement', 'Improvement'), ('Template', 'Template'), ('User', 'User-Defined Primary Instruction')], default='Template', max_length=50),
        ),
    ]
