# Generated by Django 5.2.2 on 2025-09-26 08:18

import apps.reggie.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0017_fix_teamtokensummary_null_team'),
        ('teams', '0002_add_djstripe_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamtokensummary',
            options={'verbose_name': 'Team Token Summary', 'verbose_name_plural': 'Team Token Summaries'},
        ),
        migrations.AlterModelOptions(
            name='usertokensummary',
            options={'verbose_name': 'User Token Summary', 'verbose_name_plural': 'User Token Summaries'},
        ),
        migrations.RenameIndex(
            model_name='projectinstruction',
            new_name='reggie_proj_instruc_3e7a18_idx',
            old_name='reggie_proj_instruc_9f8d2a_idx',
        ),
        migrations.RenameIndex(
            model_name='projectinstruction',
            new_name='reggie_proj_created_52ca01_idx',
            old_name='reggie_proj_created_2b4e1c_idx',
        ),
        migrations.RemoveField(
            model_name='usertokensummary',
            name='team',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(
                help_text="Upload a file to the user's file library or vault. Supported types: pdf, docx, xlsx, txt, csv, json, md, jpeg, jpg, png, gif",
                max_length=1024,
                upload_to=apps.reggie.models.choose_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(
                choices=[
                    ('pdf', 'PDF'),
                    ('docx', 'DOCX'),
                    ('xlsx', 'XLSX'),
                    ('txt', 'TXT'),
                    ('csv', 'CSV'),
                    ('json', 'JSON'),
                    ('md', 'Markdown'),
                    ('jpeg', 'JPEG'),
                    ('jpg', 'JPG'),
                    ('png', 'PNG'),
                    ('gif', 'GIF'),
                    ('other', 'Other'),
                ],
                default='pdf',
                help_text='Detected type of the uploaded file.',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='teamtokensummary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teamtokensummary',
            name='team',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name='token_summary', to='teams.team'
            ),
        ),
        migrations.AlterField(
            model_name='teamtokensummary',
            name='total_tokens',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='request_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usertokensummary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usertokensummary',
            name='period_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usertokensummary',
            name='period_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usertokensummary',
            name='total_tokens',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertokensummary',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name='token_summary', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
