# Generated by Django 5.1.5 on 2025-07-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0015_remove_vaultfile_original_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultfile',
            name='ingestion_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the ingestion process completed.', null=True),
        ),
        migrations.AddField(
            model_name='vaultfile',
            name='ingestion_error',
            field=models.TextField(blank=True, help_text='Error message if ingestion failed.', null=True),
        ),
        migrations.AddField(
            model_name='vaultfile',
            name='ingestion_progress',
            field=models.FloatField(default=0.0, help_text='Current progress of ingestion (0-100)'),
        ),
        migrations.AddField(
            model_name='vaultfile',
            name='ingestion_started_at',
            field=models.DateTimeField(blank=True, help_text='When the ingestion process started.', null=True),
        ),
        migrations.AddField(
            model_name='vaultfile',
            name='ingestion_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', help_text='Current status of the ingestion process for this file.', max_length=20),
        ),
        migrations.AddField(
            model_name='vaultfile',
            name='processed_docs',
            field=models.IntegerField(default=0, help_text='Number of documents processed'),
        ),
        migrations.AddField(
            model_name='vaultfile',
            name='total_docs',
            field=models.IntegerField(default=0, help_text='Total number of documents to process'),
        ),
    ]
