# Generated by Django 5.1.5 on 2025-07-06 16:11

from django.db import migrations, models

import apps.reggie.models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0015_alter_vaultfile_file_ephemeralfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ephemeralfile',
            name='file',
            field=models.FileField(max_length=512, upload_to=apps.reggie.models.chat_file_path),
        ),
        migrations.AlterField(
            model_name='vaultfile',
            name='file',
            field=models.FileField(max_length=1024, upload_to=apps.reggie.models.vault_file_path),
        ),
    ]
