# Generated by Django 5.1.5 on 2025-07-09 05:15

import apps.reggie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0016_alter_ephemeralfile_file_alter_vaultfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ephemeralfile',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vaultfile',
            name='file',
            field=models.FileField(max_length=1024, upload_to=apps.reggie.models.vault_file_path),
        ),
    ]
