# Generated by Django 5.1.5 on 2025-07-14 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0017_alter_ephemeralfile_title_alter_vaultfile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ephemeralfile',
            name='reggie_ephe_session_4d02c4_idx',
        ),
        migrations.AlterField(
            model_name='ephemeralfile',
            name='session_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='ephemeralfile',
            index=models.Index(fields=['session_id'], name='reggie_ephe_session_bf7646_idx'),
        ),
    ]
