# Generated by Django 5.1.5 on 2025-04-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0017_tool_teamtoolcredential_usertoolcredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='capabilities',
            field=models.ManyToManyField(blank=True, related_name='agents', to='reggie.capability'),
        ),
    ]
