# Generated by Django 5.1.5 on 2025-07-10 14:24

import apps.reggie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0017_alter_ephemeralfile_title_alter_vaultfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultfile',
            name='file',
            field=models.FileField(max_length=1024, upload_to=apps.reggie.models.vault_file_path),
        ),
    ]
