# Generated by Django 5.0.6 on 2024-09-24 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0016_alter_teamtokensummary_options_and_more'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ModelProvider',
            name='input_cost_per_1M',
            field=models.FloatField(default=0.00),
        ),
        migrations.AddField(
            model_name='ModelProvider',
            name='output_cost_per_1M',
            field=models.FloatField(default=0.00),
        )
    ]
