# Generated by Django 5.1.5 on 2025-07-19 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0016_vaultfile_ingestion_completed_at_and_more'),
        ('reggie', '0018_remove_ephemeralfile_reggie_ephe_session_4d02c4_idx_and_more'),
    ]

    operations = [
    ]
