# Generated by Django 5.1.5 on 2025-04-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0018_alter_agent_capabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprovider',
            name='embedder_dimensions',
            field=models.IntegerField(blank=True, help_text='Vector size of the embedder (e.g., 1536, 768)', null=True),
        ),
        migrations.AddField(
            model_name='modelprovider',
            name='embedder_id',
            field=models.CharField(blank=True, help_text="ID of the embedder model (e.g., 'text-embedding-ada-002', 'text-embedding-004')", max_length=100, null=True),
        ),
    ]
