# Generated by Django 5.0.6 on 2024-09-24 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0018_addfieldstomodelprovider'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='TokenUsage',
            name='chat_name',
            field=models.CharField(max_length=128, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='TokenUsage',
            name='agent_id',
            field=models.CharField(max_length=128, blank=True, null=True),
        )
    ]
