# Generated by Django 5.1.5 on 2025-07-25 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0019_merge_20250719_0108'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultProjectInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instruction', models.TextField(help_text='Instruction text for the project')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='reggie.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_project_instructions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vault Project Instruction',
                'verbose_name_plural': 'Vault Project Instructions',
                'ordering': ['-created_at'],
            },
        ),
    ]
