# Generated by Django 5.0.6 on 2024-09-24 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0019_addfieldstotokenusage'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='TokenUsage',
            name='cost',
        ),
        migrations.AddField(
            model_name='TokenUsage',
            name='cost',
            field=models.FloatField(default=0.0),
        )
    ]
