# Generated by Django 5.1.5 on 2025-07-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0020_vaultprojectinstruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultprojectinstruction',
            name='title',
            field=models.CharField(blank=True, help_text='Title for organizing instructions', max_length=100, null=True),
        ),
    ]
