# Generated by Django 5.1.5 on 2025-04-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0020_agent_updated_at_agentexpectedoutput_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentexpectedoutput',
            name='category',
            field=models.CharField(choices=[('Scope & Knowledge Boundaries', 'Scope & Knowledge Boundaries'), ('Information Retrieval & Accuracy', 'Information Retrieval & Accuracy'), ('Response Handling & Formatting', 'Response Handling & Formatting'), ('Compliance-Specific Instructions', 'Compliance-Specific Instructions'), ('Personality', 'Personality'), ('Process', 'Process'), ('Improvement', 'Improvement'), ('Template', 'Template'), ('User', 'User-Defined Primary Instruction'), ('System', 'System-Level Instruction')], default='Response Handling & Formatting', max_length=50),
        ),
        migrations.AlterField(
            model_name='agentinstruction',
            name='category',
            field=models.CharField(choices=[('Scope & Knowledge Boundaries', 'Scope & Knowledge Boundaries'), ('Information Retrieval & Accuracy', 'Information Retrieval & Accuracy'), ('Response Handling & Formatting', 'Response Handling & Formatting'), ('Compliance-Specific Instructions', 'Compliance-Specific Instructions'), ('Personality', 'Personality'), ('Process', 'Process'), ('Improvement', 'Improvement'), ('Template', 'Template'), ('User', 'User-Defined Primary Instruction'), ('System', 'System-Level Instruction')], default='Template', max_length=50),
        ),
    ]
