# Generated by Django 5.1.5 on 2025-07-30 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0021_vaultprojectinstruction_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='session_id',
            field=models.ForeignKey(blank=True, help_text='Related chat session for this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='reggie.chatsession'),
        ),
    ]
