# Generated by Django 5.1.5 on 2025-04-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0021_alter_agentexpectedoutput_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinstruction',
            name='title',
            field=models.CharField(blank=True, help_text="Optional title for the instruction, e.g., 'Default Retrieval Strategy'.", max_length=255, null=True),
        ),
    ]
