# Generated by Django 5.1.5 on 2025-04-05 05:30

import apps.reggie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0022_agentinstruction_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='unique_code',
            field=models.CharField(default=apps.reggie.models.generate_unique_code, editable=False, help_text='Unique identifier for the agent, used for session storage.', max_length=20, unique=True),
        ),
    ]
