# Generated by Django 5.1.5 on 2025-04-05 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0023_alter_agent_unique_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentinstruction',
            name='agent',
        ),
        migrations.AddField(
            model_name='agent',
            name='instructions',
            field=models.ForeignKey(blank=True, help_text='The predefined instructions assigned to this agent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='reggie.agentinstruction'),
        ),
    ]
