# Generated by Django 5.1.5 on 2025-04-05 07:40

import apps.reggie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0024_remove_agentinstruction_agent_agent_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='unique_code',
            field=models.UUIDField(default=apps.reggie.models.generate_full_uuid, editable=False, help_text='Unique identifier for the agent, used for session storage.', unique=True),
        ),
    ]
