# Generated by Django 5.1.5 on 2025-04-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0025_alter_agent_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='memory_table',
            field=models.CharField(blank=True, editable=False, help_text='Table name for memory persistence, unique to this agent.', max_length=255, unique=True),
        ),
    ]
