# Generated by Django 5.1.5 on 2025-04-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0026_agent_memory_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='read_chat_history',
            field=models.BooleanField(default=True),
        ),
    ]
