# Generated by Django 5.1.5 on 2025-04-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0027_agent_read_chat_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='read_tool_call_history',
            field=models.BooleanField(default=True),
        ),
    ]
