# Generated by Django 5.1.5 on 2025-04-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0028_agent_read_tool_call_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='knowledge_table',
            field=models.CharField(blank=True, editable=False, help_text='Table name for knowledge base persistence, derived from unique_code.', max_length=255, unique=True, null=True),
        ),
    ]
