# Generated by Django 5.1.5 on 2025-04-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0029_agent_knowledge_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='knowledge_table',
            field=models.CharField(unique=False, blank=True, editable=False, help_text='Table name for knowledge base persistence, derived from unique_code.', max_length=255, null=True),
        ),
    ]
