# Generated by Django 5.1.5 on 2025-04-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0030_alter_agent_knowledge_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique identifier for the agent, used for session storage.', max_length=64, unique=True),
        ),
    ]
