# Generated by Django 5.1.5 on 2025-04-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0031_agent_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='is_global',
            field=models.BooleanField(default=False, help_text='If true, available to all users or teams.'),
        ),
        migrations.AddField(
            model_name='website',
            name='is_system',
            field=models.BooleanField(default=False, help_text='If true, the website is added by the platform.'),
        ),
    ]
