# Generated by Django 5.1.5 on 2025-04-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reggie', '0032_chatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprovider',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the model, its strengths, or use case (e.g., best for summarization).', null=True),
        ),
    ]
