# Generated by Django 5.2.7 on 2025-10-03 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0002_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='teams',
            field=models.ManyToManyField(blank=True, help_text='Activate this flag for these teams.', to='teams.team'),
        ),
        migrations.AddField(
            model_name='flag',
            name='users',
            field=models.ManyToManyField(
                blank=True,
                help_text='Activate this flag for these users.',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Users',
            ),
        ),
        migrations.AddField(
            model_name='invitation',
            name='accepted_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='accepted_invitations',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invited_by',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sent_invitations',
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='team',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='teams.team'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='customer',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.customer'
            ),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='teams.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='subscription',
            field=models.ForeignKey(
                blank=True,
                help_text='The associated Stripe Subscription object, if it exists',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='djstripe.subscription',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('team', 'user')},
        ),
    ]
