# Generated by Django 5.2.2 on 2025-09-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NangoIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('connection_id', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nango_integration',
            },
        ),
    ]
