# Generated by Django 5.1.5 on 2025-05-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedapp',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
