# Generated by Django 5.2.6 on 2025-10-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NangoConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('connection_id', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('base_url', models.URLField(blank=True, help_text='JIRA instance base URL (e.g., https://benheath.atlassian.net)', max_length=500, null=True)),
                ('cloud_id', models.CharField(blank=True, help_text='JIRA cloud ID for API calls', max_length=255, null=True)),
                ('account_id', models.CharField(blank=True, help_text='JIRA account ID', max_length=255, null=True)),
                ('subdomain', models.CharField(blank=True, help_text='JIRA subdomain (e.g., benheath)', max_length=255, null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Connection configuration data (e.g., OAuth scopes, API settings)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Connection metadata (e.g., user info, permissions, status)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nango_connection',
            },
        ),
        migrations.DeleteModel(
            name='NangoIntegration',
        ),
    ]
