# Generated by Django 5.1.5 on 2025-05-06 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedapp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_apps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connectedapp',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_apps', to='app_integrations.supportedapp'),
        ),
        migrations.AlterUniqueTogether(
            name='connectedapp',
            unique_together={('user', 'app')},
        ),
    ]
