# Generated by Django 5.1.5 on 2025-04-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedapp',
            name='app',
            field=models.CharField(choices=[('google_drive', 'Google Drive'), ('jira', 'Jira'), ('confluence', 'Confluence')], max_length=50),
        ),
    ]
