# Generated by Django 5.2.6 on 2025-10-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_integrations', '0002_nangoconnection_delete_nangointegration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nangoconnection',
            name='config',
        ),
        migrations.AlterField(
            model_name='nangoconnection',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional provider-specific data'),
        ),
    ]
