# Generated by Django 5.1.5 on 2025-04-14 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_integrations", "0002_alter_connectedapp_app"),
        ("app_integrations", "0003_seed_supported_apps"),
    ]

    operations = []
