# Generated by Django 5.1.5 on 2025-04-29 10:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_integrations', '0005_alter_connectedapp_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connectedapp',
            unique_together={('user', 'app')},
        ),
    ]
