name: Deploy to GCP VM

on:
  push:
    branches: [main]

env:
  PROJECT_ID: bh-crypto
  REGION: us-central1
  IMAGE_NAME: bh-reggie

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: GCP Authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker --quiet

    - name: Build and Push Docker image
      run: |
        IMAGE=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest
        docker build --no-cache -f Dockerfile.web -t $IMAGE .
        docker push $IMAGE

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Upload .env file (temp)
      run: |
        echo "${{ secrets.ENV_FILE_CONTENTS }}" > env-file
        scp -o "StrictHostKeyChecking=no" env-file "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/github-actions/env-temp"

    - name: SSH and deploy image
      run: |
        ssh -o "StrictHostKeyChecking=no" "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" '
          gcloud auth activate-service-account --key-file=/home/github-actions/key.json
          gcloud auth configure-docker gcr.io --quiet
          
          docker stop bh-reggie || true
          docker rm bh-reggie || true
          docker rmi gcr.io/bh-crypto/bh-reggie:latest || true
          docker image prune -f || true

          chmod 600 /home/github-actions/env-temp
          
          cp /home/github-actions/key.json /home/github-actions/key-temp.json
          cp /home/github-actions/ssl/cert.pem /home/github-actions/ssl/cert-temp.pem
          cp /home/github-actions/ssl/key.pem /home/github-actions/ssl/key-temp.pem
          
          chmod 644 /home/github-actions/key-temp.json
          chmod 644 /home/github-actions/ssl/cert-temp.pem
          chmod 644 /home/github-actions/ssl/key-temp.pem
          
          docker pull gcr.io/bh-crypto/bh-reggie:latest
          docker run -d \
            --name bh-reggie \
            --network reggie_reggie_net \
            -p 80:8000 \
            -p 443:8443 \
            -v /home/github-actions/key-temp.json:/code/key.json:ro \
            -v /home/github-actions/ssl/cert-temp.pem:/code/ssl/cert.pem:ro \
            -v /home/github-actions/ssl/key-temp.pem:/code/ssl/key.pem:ro \
            -e GOOGLE_APPLICATION_CREDENTIALS=/code/key.json \
            -e ENABLE_HTTPS=1 \
            --env-file /home/github-actions/env-temp \
            gcr.io/bh-crypto/bh-reggie:latest
        '